export const inputs = [
	{
		id: 1,
		required,
		label: 'Type of Event',
		type: 'text',
		name: 'type-of-event',
		divStyle: '',
		labelStyle: '',
		inputStyle: '',
	},
	{
		id: 2,
		required,
		label: 'Number of Guests',
		type: 'text',
		name: 'number-of-events',
		divStyle: '',
		labelStyle: '',
		inputStyle: '',
	},
	{
		id: 3,
		label: 'Do you have somewhere to host event',
		type: 'checkbox',
		name: 'event-location-check',
		divStyle: '',
		labelStyle: '',
		inputStyle: '',
		checked: false,
	},
];
